title: AI GTM Portfolio
description: Projects, playbooks, and writing on AI-native GTM, demand generation, and RevOps.
remote_theme: pages-themes/minimal@v0.2.0



# GitHub Pages–supported plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

markdown: kramdown
