title: AI GTM
description: Projects, playbooks, and writing on AI-native GTM, demand gen, and RevOps.
remote_theme: pages-themes/minimal@v0.2.0
header_pages:
  - projects.md
  - blog.md
  - about.md
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
